id: P000506
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-16 15:43:28.670444
source_metadata:
  id: bdr:W1KG15521
  title: གྲངས་རིག་བསམ་བློའི་ཐབས་ལམ་རྣམ་བཤད།
  author: ''
  volumes:
    0a86be95d95c4d4b87c318c587f81508:
      image_group_id: I1KG15841
      title: Volume 1 of grangs rig bsam blo'i thabs lam rnam bshad/
      volume_number: 1
      total_pages: 236
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
